// Generated by scripts/abi-sync.mjs from apps/contracts/deployments/ — do not edit.
// Source of truth for protocol contract addresses, keyed by chain id.
import type { Address } from "viem";

/** One protocol deployment. Written by apps/contracts/script/Deploy.s.sol::_persist.
 *  GPU token addresses are absent by design — GPUTokens are CREATE2-deployed
 *  per gpuId and resolve at runtime via GPUIssuance.tokenOf. */
export interface ProtocolAddresses {
  chainId: number;
  gusd: Address;
  hook: Address;
  issuance: Address;
  ledger: Address;
  oracle: Address;
  /** The oracle publication identity — present only when this deployment
   *  also deployed the oracle (an external ORACLE keeps the field absent). */
  oraclePublisher?: Address;
  permit2: Address;
  poolManager: Address;
  positionManager: Address;
  quoter: Address;
  router: Address;
  sgusd: Address;
  stateView: Address;
  usdc: Address;
  weth: Address;
}
export const DEPLOYMENTS: Record<number, ProtocolAddresses> = {
  "31337": {
    "chainId": 31337,
    "gusd": "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
    "hook": "0x60C4e0F3cFb170B5940C5e50587bF930D2e690cc",
    "issuance": "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
    "ledger": "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0",
    "oracle": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    "oraclePublisher": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "permit2": "0x856e4424f806D16E8CBC702B3c0F2ede5468eae5",
    "poolManager": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    "positionManager": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
    "quoter": "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
    "router": "0x0B306BF915C4d645ff596e518fAf3F9669b97016",
    "sgusd": "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
    "stateView": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
    "usdc": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "weth": "0x0165878A594ca255338adfa4d48449f69242Eb8F"
  }
};
