// Generated by scripts/abi-sync.mjs from apps/contracts/deployments/ — do not edit.
// Source of truth for protocol contract addresses, keyed by chain id.
import type { Address } from "viem";

/** One protocol deployment. Written by apps/contracts/script/Deploy.s.sol::_persist.
 *  GPU token addresses are absent by design — GPUTokens are CREATE2-deployed
 *  per gpuId and resolve at runtime via GPUIssuance.tokenOf. */
export interface ProtocolAddresses {
  chainId: number;
  gusd: Address;
  hook: Address;
  issuance: Address;
  ledger: Address;
  oracle: Address;
  /** The oracle publication identity — present only when this deployment
   *  also deployed the oracle (an external ORACLE keeps the field absent). */
  oraclePublisher?: Address;
  permit2: Address;
  poolManager: Address;
  positionManager: Address;
  quoter: Address;
  router: Address;
  sgusd: Address;
  stateView: Address;
  underlying: Address;
  stableRouter: Address;
  /** Funding assets whitelisted on this deployment's StableRouter — the
   *  underlying first (constructor-whitelisted). Trust boundary: identity
   *  comes from this record, never from token symbols. */
  stables: Address[];
  weth: Address;
}
export const DEPLOYMENTS: Record<number, ProtocolAddresses> = {
  "31337": {
    "chainId": 31337,
    "gusd": "0xeC1BB74f5799811c0c1Bff94Ef76Fb40abccbE4a",
    "hook": "0x34837387d9b3AAfdD1c4EB1F1BA26360479410cc",
    "issuance": "0x3E661784267F128e5f706De17Fac1Fc1c9d56f30",
    "ledger": "0x09120eAED8e4cD86D85a616680151DAA653880F2",
    "oracle": "0x1D3EDBa836caB11C26A186873abf0fFeB8bbaE63",
    "oraclePublisher": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "permit2": "0xc6c651d671b1a4a71218ACe23a162bF68A07E163",
    "poolManager": "0x9C85258d9A00C01d00ded98065ea3840dF06f09c",
    "positionManager": "0x666432Ccb747B2220875cE185f487Ed53677faC9",
    "quoter": "0x398E4948e373Db819606A459456176D31C3B1F91",
    "router": "0x15Ff10fCc8A1a50bFbE07847A22664801eA79E0f",
    "sgusd": "0xF6a8aD553b265405526030c2102fda2bDcdDC177",
    "stableRouter": "0xAe9Ed85dE2670e3112590a2BB17b7283ddF44d9c",
    "stables": [
      "0x0F527785e39B22911946feDf580d87a4E00465f0"
    ],
    "stateView": "0xFCFE742e19790Dd67a627875ef8b45F17DB1DaC6",
    "underlying": "0x0F527785e39B22911946feDf580d87a4E00465f0",
    "weth": "0x01cf58e264d7578D4C67022c58A24CbC4C4a304E"
  }
};
