// Generated by scripts/abi-sync.mjs from apps/contracts/out/GpuRouter.sol/GpuRouter.json — do not edit.
export const GPU_ROUTER_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "poolManager_",
        "type": "address",
        "internalType": "contract IPoolManager"
      },
      {
        "name": "gUSD_",
        "type": "address",
        "internalType": "contract GUSD"
      },
      {
        "name": "issuance_",
        "type": "address",
        "internalType": "contract GPUIssuance"
      },
      {
        "name": "hook_",
        "type": "address",
        "internalType": "contract GPUHook"
      },
      {
        "name": "usdc_",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "error",
    "name": "DustLeft",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LegMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaxPaidExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotCanonicalPool",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPoolManager",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PoolShortfall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "Slippage",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownGpu",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnsupportedPayment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroGpuOut",
    "inputs": []
  },
  {
    "type": "event",
    "name": "Buy",
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "payer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "gpuOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "paid",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "poolGpuOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "issueGpuOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "hookFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "issuanceFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Sell",
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "gpuIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "out",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "hookFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "function",
    "name": "buy",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct GpuRouter.BuyParams",
        "components": [
          {
            "name": "gpuId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gpuOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "poolGpuOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueGpuOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "payment",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "maxPaid",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sqrtLimitX96",
            "type": "uint160",
            "internalType": "uint160"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "paid",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "buyExactIn",
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "gusdMaxIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minGpuOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sqrtLimitX96",
        "type": "uint160",
        "internalType": "uint160"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "gpuOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "gUSD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract GUSD"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hook",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract GPUHook"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "issuance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract GPUIssuance"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "poolManager",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPoolManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sell",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct GpuRouter.SellParams",
        "components": [
          {
            "name": "gpuId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gpuIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "payout",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "minOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sqrtLimitX96",
            "type": "uint160",
            "internalType": "uint160"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "unlockCallback",
    "inputs": [
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "usdc",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  }
] as const;
