// Generated by scripts/abi-sync.mjs from apps/contracts/out/GpuOracle.sol/GpuOracle.json — do not edit.
export const GPU_ORACLE_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "initialOwner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "signer_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "epochLength_",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "maxObservationAge_",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "error",
    "name": "BadEpochBinding",
    "inputs": [
      {
        "name": "validFrom",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "validUntil",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "EpochAlreadyBound",
    "inputs": [
      {
        "name": "boundHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "actualHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EpochLengthZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FutureObservation",
    "inputs": [
      {
        "name": "observedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "nowTs",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "GpuMismatch",
    "inputs": [
      {
        "name": "expected",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "actual",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidSigner",
    "inputs": [
      {
        "name": "recovered",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "expected",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidVersion",
    "inputs": [
      {
        "name": "actual",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotPendingSigner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSigner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ObservationAgeBelowEpoch",
    "inputs": [
      {
        "name": "maxObservationAge",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "epochLength",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "StaleObservation",
    "inputs": [
      {
        "name": "observedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "minObservedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownGpuEpoch",
    "inputs": [
      {
        "name": "current",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "actual",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroPrice",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroSigner",
    "inputs": []
  },
  {
    "type": "event",
    "name": "EpochLengthSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "seconds_",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "event",
    "name": "MaxObservationAgeSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "seconds_",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "anonymous": false,
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "anonymous": false,
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "PriceConsumed",
    "anonymous": false,
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "internalType": "bytes32",
        "indexed": true
      },
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "epoch",
        "type": "uint64",
        "internalType": "uint64",
        "indexed": true
      },
      {
        "name": "observedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "reportHash",
        "type": "bytes32",
        "internalType": "bytes32",
        "indexed": true
      },
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "event",
    "name": "SignerAccepted",
    "anonymous": false,
    "inputs": [
      {
        "name": "previousSigner",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "newSigner",
        "type": "address",
        "internalType": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "SignerTransferStarted",
    "anonymous": false,
    "inputs": [
      {
        "name": "currentSigner",
        "type": "address",
        "internalType": "address",
        "indexed": true
      },
      {
        "name": "nextSigner",
        "type": "address",
        "internalType": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": []
  },
  {
    "type": "function",
    "name": "acceptSigner",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": []
  },
  {
    "type": "function",
    "name": "consume",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "report",
        "type": "tuple",
        "internalType": "struct IGpuOracle.Report",
        "components": [
          {
            "name": "version",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "gpuId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "observedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "epoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validFrom",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "calcHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "currentEpoch",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "epochLength",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "lastConsumedAt",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "lastConsumedEpoch",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "lastConsumedPrice",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "lastConsumedReportHash",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "maxObservationAge",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "owner",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "pendingSigner",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": []
  },
  {
    "type": "function",
    "name": "reportDigest",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "report",
        "type": "tuple",
        "internalType": "struct IGpuOracle.Report",
        "components": [
          {
            "name": "version",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "gpuId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "observedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "epoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validFrom",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "calcHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "reportHash",
    "stateMutability": "pure",
    "inputs": [
      {
        "name": "report",
        "type": "tuple",
        "internalType": "struct IGpuOracle.Report",
        "components": [
          {
            "name": "version",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "gpuId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "observedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "epoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validFrom",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "calcHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "setEpochLength",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "seconds_",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "setMaxObservationAge",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "seconds_",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "signer",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "transferSigner",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "next",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "verify",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "gpuId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "report",
        "type": "tuple",
        "internalType": "struct IGpuOracle.Report",
        "components": [
          {
            "name": "version",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "gpuId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "observedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "epoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validFrom",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "calcHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
