// Generated by scripts/abi-sync.mjs from apps/contracts/out/GpuQuoter.sol/GpuQuoter.json — do not edit.
export const GPU_QUOTER_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "poolManager_",
        "type": "address",
        "internalType": "contract IPoolManager"
      },
      {
        "name": "gUSD_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "issuance_",
        "type": "address",
        "internalType": "contract GPUIssuance"
      },
      {
        "name": "initialOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "error",
    "name": "NoFloat",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotGpuPool",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPoolManager",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSelf",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "QuoteGpu",
    "inputs": [
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct GpuQuoter.QuoteResult",
        "components": [
          {
            "name": "isBuy",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "exactIn",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "gusdIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gusdOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "nativeGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "backstopGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hookFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueBase",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "endTick",
            "type": "int24",
            "internalType": "int24"
          }
        ]
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnexpectedCallSuccess",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "function",
    "name": "_quoteBuy",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "gusdIn",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "_quoteBuyExactOut",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "gpuDemand",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "_quoteSell",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "gpuIn",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "_quoteSellExactOut",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "gusdDemand",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "gUSD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "issuance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract GPUIssuance"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "poolManager",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPoolManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteBuy",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "gusdIn",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct GpuQuoter.QuoteResult",
        "components": [
          {
            "name": "isBuy",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "exactIn",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "gusdIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gusdOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "nativeGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "backstopGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hookFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueBase",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "endTick",
            "type": "int24",
            "internalType": "int24"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "quoteBuyExactOut",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "gpuDemand",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct GpuQuoter.QuoteResult",
        "components": [
          {
            "name": "isBuy",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "exactIn",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "gusdIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gusdOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "nativeGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "backstopGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hookFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueBase",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "endTick",
            "type": "int24",
            "internalType": "int24"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "quoteSell",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "gpuIn",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct GpuQuoter.QuoteResult",
        "components": [
          {
            "name": "isBuy",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "exactIn",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "gusdIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gusdOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "nativeGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "backstopGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hookFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueBase",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "endTick",
            "type": "int24",
            "internalType": "int24"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "quoteSellExactOut",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "gusdDemand",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct GpuQuoter.QuoteResult",
        "components": [
          {
            "name": "isBuy",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "exactIn",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "gusdIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gusdOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gpuOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "nativeGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "backstopGpu",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "polFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hookFeeGusd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueBase",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "issueFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "endTick",
            "type": "int24",
            "internalType": "int24"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setGpuFloat",
    "inputs": [
      {
        "name": "gpuToken",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setGusdFloat",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sweep",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "unlockCallback",
    "inputs": [
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "nonpayable"
  }
] as const;
