type PmPoolInitialized @index(fields: ["poolId"]) {
  id: String!
  blockNumber: Int!
  logIndex: Int!
  blockTimestamp: BigInt!
  poolId: Bytes!
  currency0: Bytes
  currency1: Bytes
  fee: Int
  tickSpacing: Int
  hooks: Bytes
  sqrtPriceX96: BigInt
  tick: Int
}

type PmSwap @index(fields: ["poolId"]) {
  id: String!
  blockNumber: Int!
  logIndex: Int!
  blockTimestamp: BigInt!
  txHash: String!
  poolId: Bytes!
  sender: Bytes!
  amount0: BigInt!
  amount1: BigInt!
  sqrtPriceX96: BigInt!
  liquidity: BigInt!
  tick: Int!
  fee: Int!
}

type GusdMinted @index(fields: ["user"]) {
  id: String!
  blockNumber: Int!
  logIndex: Int!
  blockTimestamp: BigInt!
  user: Bytes!
  underlyingIn: BigInt!
  gusdOut: BigInt!
  fee: BigInt!
}
